### ISSUE TITLE
Linux/macOS support

### ISSUE THREAD

**Issue by jjustin** [SloCompTech/sct_tester#1]
First, thanks for the work you put in the project

I tried running the extension on macOS, but it failed due to tj being exe file.

Would it be possible to include OS check and appending e.g. `mono`(mono is framework recommended in the guidelines on how to use tj.exe on linux) to the beginning of executed command if detected os is mac or linux.

**Comment by SloCompTech** [comment]
Sure thing, I will do it tommorow and then I will notify you, so you will be able to test it that it is working.

**Comment by SloCompTech** [comment]
Hi there, please try version 1.0.2 and report if it is working.

**Comment by jjustin** [comment]
Works 👍
